config.webserver.ip_allowed = ['0.0.0.0'];
config.webserver.logio_port = 28778;
config.webserver.tty_port = 8000;
config.phone_release_time = 108000;//30 mins number busy (registration)
config.soundpath = '/opt/plentystars/store/sounds/custom';
config.exec_script_path = '/usr/bin/';
config.rrd_path = '/var/spool/asteraid/';
config.store = {};
config.store.path = '/opt/plentystars/store/';
config.multi = false;
config.server_hosts_file = "/etc/ansible/hosts";
config.voice_path = "/opt/plentystars/store/monitor/";
config.fax_path = "/opt/plentystars/store/fax/";
config.test_gitignore = '';